# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_files.rag_pb2 as rag__pb2


class RagServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Vectorize = channel.unary_unary(
                '/Rag.RagService/Vectorize',
                request_serializer=rag__pb2.VectorizeRequest.SerializeToString,
                response_deserializer=rag__pb2.VectorizeResponse.FromString,
                )
        self.GetAnswer = channel.unary_unary(
                '/Rag.RagService/GetAnswer',
                request_serializer=rag__pb2.GetAnswerRequest.SerializeToString,
                response_deserializer=rag__pb2.GetAnswerResponse.FromString,
                )


class RagServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Vectorize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Vectorize': grpc.unary_unary_rpc_method_handler(
                    servicer.Vectorize,
                    request_deserializer=rag__pb2.VectorizeRequest.FromString,
                    response_serializer=rag__pb2.VectorizeResponse.SerializeToString,
            ),
            'GetAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnswer,
                    request_deserializer=rag__pb2.GetAnswerRequest.FromString,
                    response_serializer=rag__pb2.GetAnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Rag.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Vectorize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Rag.RagService/Vectorize',
            rag__pb2.VectorizeRequest.SerializeToString,
            rag__pb2.VectorizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Rag.RagService/GetAnswer',
            rag__pb2.GetAnswerRequest.SerializeToString,
            rag__pb2.GetAnswerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
