# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rag.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x03Rag\"%\n\x10VectorizeRequest\x12\x11\n\tdocuments\x18\x01 \x03(\t\"#\n\x11VectorizeResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"$\n\x10GetAnswerRequest\x12\x10\n\x08\x64ocument\x18\x01 \x01(\t\"7\n\x0fSimilarDocument\x12\x10\n\x08\x64ocument\x18\x01 \x01(\t\x12\x12\n\nsimilarity\x18\x02 \x01(\x02\":\n\x11GetAnswerResponse\x12%\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x14.Rag.SimilarDocument2\x84\x01\n\nRagService\x12:\n\tVectorize\x12\x15.Rag.VectorizeRequest\x1a\x16.Rag.VectorizeResponse\x12:\n\tGetAnswer\x12\x15.Rag.GetAnswerRequest\x1a\x16.Rag.GetAnswerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORIZEREQUEST']._serialized_start=18
  _globals['_VECTORIZEREQUEST']._serialized_end=55
  _globals['_VECTORIZERESPONSE']._serialized_start=57
  _globals['_VECTORIZERESPONSE']._serialized_end=92
  _globals['_GETANSWERREQUEST']._serialized_start=94
  _globals['_GETANSWERREQUEST']._serialized_end=130
  _globals['_SIMILARDOCUMENT']._serialized_start=132
  _globals['_SIMILARDOCUMENT']._serialized_end=187
  _globals['_GETANSWERRESPONSE']._serialized_start=189
  _globals['_GETANSWERRESPONSE']._serialized_end=247
  _globals['_RAGSERVICE']._serialized_start=250
  _globals['_RAGSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
