apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backendIngress
  labels:
    name: backendIngress
spec:
  rules:
  - host: 127.0.0.0
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: backend
            port: 
              number: 8000
