apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jorjo2009/backend-service:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: rag_addr
          value: "rag"
        - name: rag_port
          value: "50001"
        - name: model_addr
          value: "model"
        - name: model_port
          value: "50001"
        - name: database_name
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: database_url
          value: "database"
        - name: database_port
          value: "3306"
        - name: database_user
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
        - name: database_password
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret


