
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        release: development
    spec:
      containers:
      - name: backend
        image: jorjo2009/backend-service:latest
        command: [ "uvicorn", "app:app","--host", "0.0.0.0", "--reload" ]
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: rag_addr
          value: "rag"
        - name: rag_port
          value: "50001"
        - name: model_addr
          value: "model"
        - name: model_port
          value: "50001"
        - name: database_name
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: database_url
          value: "mysql"
        - name: database_port
          value: "3306"
        - name: database_user
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
        - name: database_password
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
        volumeMounts:
        - mountPath: /app
          name: code
      volumes:
      - name: code
        hostPath:
          path:  /run/desktop/mnt/host/c/Users/georg/code/lm-with-rag/backend
        
      





